video:
  resolution: 1600x900
  fps: 60
  fullscreen: false
  display: 0
  vsync: false
  hardware_rendering: true

audio:
  music: 1.0
  sound: 1.0

gui:
  language: Russian

input:
    up: up
    down: down
    left: left
    right: right
    confirm: return
    back: escape
    pause: escape
    jump: up
    poop: space